In [1]:
import jax.numpy as jnp
from jax import jit, vmap

import sys
sys.path.append('..')
from utils.units_constants import *

In [24]:
from utils.nfw import rho_integral

In [21]:
x = jnp.arange(6)
y = x + 1

In [25]:
z = jnp.stack([x, y], axis=-1)
z

DeviceArray([[0, 1],
             [1, 2],
             [2, 3],
             [3, 4],
             [4, 5],
             [5, 6]], dtype=int32)

In [26]:
rho_integral(z)

DeviceArray([ 9.312056 ,  5.1329365,  8.111118 , 10.710487 ,  5.246497 ,
              7.1530776], dtype=float32)

In [2]:
x = jnp.array([
    [1.0, 2.0],
    [2.0, 2.0],
    [2.0, 3.0],
    [3.0, 4.0]
])

In [3]:
norm = vmap(jnp.linalg.norm)

In [4]:
norm(x)

DeviceArray([2.236068 , 2.828427 , 3.6055512, 5.       ], dtype=float32)

In [2]:
arcmin

0.0002908882086657216